version = 0.1

[default.deploy.parameters]
stack_name = "janvani-bharat-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zzgrnpqem8mu"
s3_prefix = "janvani-bharat-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
confirm_changeset = true
image_repositories = []


[default.global.parameters]
region = "us-east-1"
[dev.deploy.parameters]
stack_name = "janvani-bharat-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "janvani-bharat-dev"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = false

[prod.deploy.parameters]
stack_name = "janvani-bharat-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "janvani-bharat-prod"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = true
