export type Language = 'english' | 'hindi' | 'tamil' | 'telugu' | 'bengali' | 'marathi' | 'gujarati' | 'kannada';

type LangMap = Record<Language, string>;
const p = (map: LangMap, lang: Language): string => map[lang] ?? map.english;

export const t = (lang: Language) => ({
  // Navbar / common
  checkEligibility: p({ english: 'Check Eligibility', hindi: 'पात्रता जांचें', tamil: 'தகுதி சரிபார்க்கவும்', telugu: 'అర్హత తనిఖీ', bengali: 'যোগ্যতা পরীক্ষা', marathi: 'पात्रता तपासा', gujarati: 'પાત્રતા તપાસો', kannada: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ' }, lang),
  heroTitle: p({ english: 'JanVani Bharat', hindi: 'जनवाणी भारत', tamil: 'ஜன்வாணி பாரத்', telugu: 'జన్వాణి భారత్', bengali: 'জনবাণী ভারত', marathi: 'जनवाणी भारत', gujarati: 'જનવાણી ભારત', kannada: 'ಜನವಾಣಿ ಭಾರತ' }, lang),
  heroSubtitle: p({ english: 'AI-powered platform to discover government schemes for every citizen.', hindi: 'हर नागरिक के लिए सरकारी योजनाएं खोजने का AI-संचालित मंच।', tamil: 'ஒவ்வொரு குடிமகனுக்கும் அரசு திட்டங்களை கண்டறிய AI தளம்.', telugu: 'ప్రతి పౌరుడికి ప్రభుత్వ పథకాలను కనుగొనడానికి AI వేదిక.', bengali: 'প্রতিটি নাগরিকের জন্য সরকারি প্রকল্প আবিষ্কার করতে AI প্ল্যাটফর্ম।', marathi: 'प्रत्येक नागरिकासाठी सरकारी योजना शोधण्यासाठी AI व्यासपीठ.', gujarati: 'દરેક નાગરિક માટે સરકારી યોજનાઓ શોધવા AI પ્લેટફોર્મ.', kannada: 'ಪ್ರತಿ ನಾಗರಿಕರಿಗೆ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು AI ವೇದಿಕೆ.' }, lang),
  startCheck: p({ english: 'Start Eligibility Check', hindi: 'पात्रता जांच शुरू करें', tamil: 'தகுதி சரிபார்ப்பை தொடங்கு', telugu: 'అర్హత తనిఖీ ప్రారంభించండి', bengali: 'যোগ্যতা পরীক্ষা শুরু করুন', marathi: 'पात्रता तपासणी सुरू करा', gujarati: 'પાત્રતા તપાસ શરૂ કરો', kannada: 'ಅರ್ಹತೆ ಪರಿಶೀಲನೆ ಪ್ರಾರಂಭಿಸಿ' }, lang),
  schemesCount: p({ english: '24+ Schemes', hindi: '24+ योजनाएं', tamil: '24+ திட்டங்கள்', telugu: '24+ పథకాలు', bengali: '24+ প্রকল্প', marathi: '24+ योजना', gujarati: '24+ યોજનાઓ', kannada: '24+ ಯೋಜನೆಗಳು' }, lang),
  languages: p({ english: '8 Languages', hindi: '8 भाषाएं', tamil: '8 மொழிகள்', telugu: '8 భాషలు', bengali: '8 ভাষা', marathi: '8 भाषा', gujarati: '8 ભાષાઓ', kannada: '8 ಭಾಷೆಗಳು' }, lang),
  free: p({ english: '100% Free', hindi: '100% मुफ्त', tamil: '100% இலவசம்', telugu: '100% ఉచితం', bengali: '100% বিনামূল্যে', marathi: '100% मोफत', gujarati: '100% મફત', kannada: '100% ಉಚಿತ' }, lang),
  // Why section
  whyTitle: p({ english: 'Why JanVani Bharat?', hindi: 'जनवाणी भारत क्यों?', tamil: 'ஏன் ஜன்வாணி பாரத்?', telugu: 'జన్వాణి భారత్ ఎందుకు?', bengali: 'কেন জনবাণী ভারত?', marathi: 'जनवाणी भारत का?', gujarati: 'જનવાણી ભારત કેમ?', kannada: 'ಜನವಾಣಿ ಭಾರತ ಏಕೆ?' }, lang),
  whySubtitle: p({ english: 'Bridging the gap between citizens and government welfare schemes using AI.', hindi: 'AI का उपयोग करके नागरिकों और सरकारी कल्याण योजनाओं के बीच की खाई को पाटना।', tamil: 'AI பயன்படுத்தி குடிமக்களுக்கும் அரசு நலத் திட்டங்களுக்கும் இடையிலான இடைவெளியை குறைக்கிறோம்.', telugu: 'AI ఉపయోగించి పౌరులకు మరియు ప్రభుత్వ సంక్షేమ పథకాలకు మధ్య అంతరాన్ని తగ్గించడం.', bengali: 'AI ব্যবহার করে নাগরিক এবং সরকারি কল্যাণ প্রকল্পের মধ্যে ব্যবধান কমানো।', marathi: 'AI वापरून नागरिक आणि सरकारी कल्याण योजनांमधील अंतर कमी करणे.', gujarati: 'AI નો ઉપયોગ કરીને નાગરિકો અને સરકારી કલ્યાણ યોજનાઓ વચ્ચેનું અંતર ઘટાડવું.', kannada: 'AI ಬಳಸಿ ನಾಗರಿಕರು ಮತ್ತು ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳ ನಡುವಿನ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡುವುದು.' }, lang),
  features: [
    {
      title: p({ english: 'Smart Eligibility Checker', hindi: 'स्मार्ट पात्रता जांचकर्ता', tamil: 'ஸ்மார்ட் தகுதி சரிபார்ப்பு', telugu: 'స్మార్ట్ అర్హత తనిఖీ', bengali: 'স্মার্ট যোগ্যতা পরীক্ষক', marathi: 'स्मार्ट पात्रता तपासक', gujarati: 'સ્માર્ટ પાત્રતા તપાસ', kannada: 'ಸ್ಮಾರ್ಟ್ ಅರ್ಹತೆ ಪರೀಕ್ಷಕ' }, lang),
      desc: p({ english: 'Enter simple details and instantly discover schemes you qualify for.', hindi: 'सरल विवरण दर्ज करें और तुरंत योजनाएं खोजें।', tamil: 'எளிய விவரங்களை உள்ளிட்டு உடனடியாக திட்டங்களை கண்டறியுங்கள்.', telugu: 'సాధారణ వివరాలు నమోదు చేసి వెంటనే పథకాలు కనుగొనండి.', bengali: 'সহজ তথ্য দিন এবং তাৎক্ষণিকভাবে প্রকল্প খুঁজুন।', marathi: 'साधे तपशील भरा आणि लगेच योजना शोधा.', gujarati: 'સરળ વિગતો દાખલ કરો અને તરત જ યોજનાઓ શોધો.', kannada: 'ಸರಳ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ ಮತ್ತು ತಕ್ಷಣ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.' }, lang),
    },
    {
      title: p({ english: 'Multilingual Support', hindi: 'बहुभाषी समर्थन', tamil: 'பல மொழி ஆதரவு', telugu: 'బహుభాషా మద్దతు', bengali: 'বহুভাষিক সমর্থন', marathi: 'बहुभाषिक समर्थन', gujarati: 'બહુભાષી સમર્થન', kannada: 'ಬಹುಭಾಷಾ ಬೆಂಬಲ' }, lang),
      desc: p({ english: 'Get explanations in 8 Indian languages.', hindi: '8 भारतीय भाषाओं में स्पष्टीकरण पाएं।', tamil: '8 இந்திய மொழிகளில் விளக்கங்கள் பெறுங்கள்.', telugu: '8 భారతీయ భాషలలో వివరణలు పొందండి.', bengali: '8 ভারতীয় ভাষায় ব্যাখ্যা পান।', marathi: '8 भारतीय भाषांमध्ये स्पष्टीकरण मिळवा.', gujarati: '8 ભારતીય ભાષાઓમાં સ્પષ્ટીકરણ મેળવો.', kannada: '8 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ವಿವರಣೆ ಪಡೆಯಿರಿ.' }, lang),
    },
    {
      title: p({ english: 'AI-Powered Explanations', hindi: 'AI-संचालित स्पष्टीकरण', tamil: 'AI விளக்கங்கள்', telugu: 'AI వివరణలు', bengali: 'AI ব্যাখ্যা', marathi: 'AI स्पष्टीकरण', gujarati: 'AI સ્પષ્ટીકરણ', kannada: 'AI ವಿವರಣೆಗಳು' }, lang),
      desc: p({ english: 'Understand benefits and how to apply in simple language.', hindi: 'लाभ और आवेदन प्रक्रिया सरल भाषा में समझें।', tamil: 'நன்மைகள் மற்றும் விண்ணப்பிக்கும் முறையை எளிய மொழியில் புரிந்துகொள்ளுங்கள்.', telugu: 'ప్రయోజనాలు మరియు దరఖాస్తు ప్రక్రియను సులభ భాషలో అర్థం చేసుకోండి.', bengali: 'সুবিধা এবং আবেদন প্রক্রিয়া সহজ ভাষায় বুঝুন।', marathi: 'फायदे आणि अर्ज प्रक्रिया सोप्या भाषेत समजून घ्या.', gujarati: 'ફાયદા અને અરજી પ્રક્રિયા સરળ ભાષામાં સમજો.', kannada: 'ಪ್ರಯೋಜನಗಳು ಮತ್ತು ಅರ್ಜಿ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.' }, lang),
    },
    {
      title: p({ english: 'Trusted & Secure', hindi: 'विश्वसनीय और सुरक्षित', tamil: 'நம்பகமான & பாதுகாப்பான', telugu: 'విశ్వసనీయ & సురక్షిత', bengali: 'বিশ্বস্ত ও নিরাপদ', marathi: 'विश्वासार्ह आणि सुरक्षित', gujarati: 'વિશ્વસનીય અને સુરક્ષિત', kannada: 'ವಿಶ್ವಾಸಾರ್ಹ ಮತ್ತು ಸುರಕ್ಷಿತ' }, lang),
      desc: p({ english: 'Your data stays private. We only use it to find the right schemes for you.', hindi: 'आपका डेटा निजी रहता है। हम इसे केवल सही योजनाएं खोजने के लिए उपयोग करते हैं।', tamil: 'உங்கள் தரவு தனிப்பட்டதாக இருக்கும். சரியான திட்டங்களை கண்டறிய மட்டுமே பயன்படுத்துகிறோம்.', telugu: 'మీ డేటా ప్రైవేట్‌గా ఉంటుంది. సరైన పథకాలు కనుగొనడానికి మాత్రమే ఉపయోగిస్తాము.', bengali: 'আপনার তথ্য ব্যক্তিগত থাকে। শুধুমাত্র সঠিক প্রকল্প খুঁজতে ব্যবহার করি।', marathi: 'तुमचा डेटा खाजगी राहतो. योग्य योजना शोधण्यासाठीच वापरतो.', gujarati: 'તમારો ડેટા ખાનગી રહે છે. માત્ર સાચી યોજનાઓ શોધવા ઉપયોગ કરીએ છીએ.', kannada: 'ನಿಮ್ಮ ಡೇಟಾ ಖಾಸಗಿಯಾಗಿ ಉಳಿಯುತ್ತದೆ. ಸರಿಯಾದ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಮಾತ್ರ ಬಳಸುತ್ತೇವೆ.' }, lang),
    },
  ],
  // How it works
  howTitle: p({ english: 'How It Works', hindi: 'यह कैसे काम करता है', tamil: 'இது எப்படி வேலை செய்கிறது', telugu: 'ఇది ఎలా పని చేస్తుంది', bengali: 'এটি কীভাবে কাজ করে', marathi: 'हे कसे कार्य करते', gujarati: 'આ કેવી રીતે કામ કરે છે', kannada: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ' }, lang),
  howSubtitle: p({ english: 'Three simple steps to discover your eligible schemes', hindi: 'तीन सरल चरणों में योजनाएं खोजें', tamil: 'மூன்று எளிய படிகளில் திட்டங்களை கண்டறியுங்கள்', telugu: 'మూడు సులభ దశలలో పథకాలు కనుగొనండి', bengali: 'তিনটি সহজ ধাপে প্রকল্প খুঁজুন', marathi: 'तीन सोप्या पायऱ्यांमध्ये योजना शोधा', gujarati: 'ત્રણ સરળ પગલામાં યોજનાઓ શોધો', kannada: 'ಮೂರು ಸರಳ ಹಂತಗಳಲ್ಲಿ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ' }, lang),
  steps: [
    {
      title: p({ english: 'Enter Your Details', hindi: 'अपना विवरण दर्ज करें', tamil: 'உங்கள் விவரங்களை உள்ளிடுங்கள்', telugu: 'మీ వివరాలు నమోదు చేయండి', bengali: 'আপনার তথ্য দিন', marathi: 'तुमचे तपशील भरा', gujarati: 'તમારી વિગતો દાખલ કરો', kannada: 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ' }, lang),
      desc: p({ english: 'Fill a simple form with basic information like age, income, and occupation.', hindi: 'आयु, आय और व्यवसाय जैसी बुनियादी जानकारी के साथ एक सरल फॉर्म भरें।', tamil: 'வயது, வருமானம் மற்றும் தொழில் போன்ற அடிப்படை தகவல்களுடன் எளிய படிவம் நிரப்புங்கள்.', telugu: 'వయసు, ఆదాయం మరియు వృత్తి వంటి ప్రాథమిక సమాచారంతో సాధారణ ఫారమ్ నింపండి.', bengali: 'বয়স, আয় এবং পেশার মতো মৌলিক তথ্য দিয়ে একটি সহজ ফর্ম পূরণ করুন।', marathi: 'वय, उत्पन्न आणि व्यवसाय यासारख्या मूलभूत माहितीसह एक साधा फॉर्म भरा.', gujarati: 'ઉંમર, આવક અને વ્યવસાય જેવી મૂળભૂત માહિતી સાથે સરળ ફોર્મ ભરો.', kannada: 'ವಯಸ್ಸು, ಆದಾಯ ಮತ್ತು ಉದ್ಯೋಗದಂತಹ ಮೂಲ ಮಾಹಿತಿಯೊಂದಿಗೆ ಸರಳ ಫಾರ್ಮ್ ತುಂಬಿರಿ.' }, lang),
    },
    {
      title: p({ english: 'AI Analyzes Eligibility', hindi: 'AI पात्रता का विश्लेषण करता है', tamil: 'AI தகுதியை பகுப்பாய்வு செய்கிறது', telugu: 'AI అర్హతను విశ్లేషిస్తుంది', bengali: 'AI যোগ্যতা বিশ্লেষণ করে', marathi: 'AI पात्रता विश्लेषण करते', gujarati: 'AI પાત્રતા વિશ્લેષણ કરે છે', kannada: 'AI ಅರ್ಹತೆಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ' }, lang),
      desc: p({ english: 'Our AI matches your profile against all available government schemes.', hindi: 'हमारा AI आपकी प्रोफ़ाइल को सभी उपलब्ध सरकारी योजनाओं से मिलाता है।', tamil: 'எங்கள் AI உங்கள் சுயவிவரத்தை அனைத்து அரசு திட்டங்களுடன் பொருத்துகிறது.', telugu: 'మా AI మీ ప్రొఫైల్‌ను అన్ని ప్రభుత్వ పథకాలతో సరిపోల్చుతుంది.', bengali: 'আমাদের AI আপনার প্রোফাইল সব সরকারি প্রকল্পের সাথে মেলায়।', marathi: 'आमचे AI तुमची प्रोफाइल सर्व सरकारी योजनांशी जुळवते.', gujarati: 'અમારું AI તમારી પ્રોફાઇલ તમામ સરકારી યોજનાઓ સાથે મેળ ખાય છે.', kannada: 'ನಮ್ಮ AI ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಎಲ್ಲಾ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳೊಂದಿಗೆ ಹೊಂದಿಸುತ್ತದೆ.' }, lang),
    },
    {
      title: p({ english: 'Get Recommendations', hindi: 'सिफारिशें प्राप्त करें', tamil: 'பரிந்துரைகளை பெறுங்கள்', telugu: 'సిఫార్సులు పొందండి', bengali: 'সুপারিশ পান', marathi: 'शिफारसी मिळवा', gujarati: 'ભલામણો મેળવો', kannada: 'ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ' }, lang),
      desc: p({ english: 'View eligible schemes with clear explanations and direct apply links.', hindi: 'स्पष्ट स्पष्टीकरण और सीधे आवेदन लिंक के साथ पात्र योजनाएं देखें।', tamil: 'தெளிவான விளக்கங்கள் மற்றும் நேரடி விண்ணப்ப இணைப்புகளுடன் தகுதியான திட்டங்களை பாருங்கள்.', telugu: 'స్పష్టమైన వివరణలు మరియు నేరుగా దరఖాస్తు లింక్‌లతో అర్హత పొందిన పథకాలు చూడండి.', bengali: 'স্পষ্ট ব্যাখ্যা এবং সরাসরি আবেদন লিঙ্ক সহ যোগ্য প্রকল্পগুলি দেখুন।', marathi: 'स्पष्ट स्पष्टीकरण आणि थेट अर्ज लिंकसह पात्र योजना पहा.', gujarati: 'સ્પષ્ટ સ્પષ્ટીકરણ અને સીધી અરજી લિંક સાથે પાત્ર યોજનાઓ જુઓ.', kannada: 'ಸ್ಪಷ್ಟ ವಿವರಣೆಗಳು ಮತ್ತು ನೇರ ಅರ್ಜಿ ಲಿಂಕ್‌ಗಳೊಂದಿಗೆ ಅರ್ಹ ಯೋಜನೆಗಳನ್ನು ನೋಡಿ.' }, lang),
    },
  ],
  checkNow: p({ english: 'Check Your Eligibility Now', hindi: 'अभी पात्रता जांचें', tamil: 'இப்போதே தகுதி சரிபார்க்கவும்', telugu: 'ఇప్పుడే అర్హత తనిఖీ చేయండి', bengali: 'এখনই যোগ্যতা পরীক্ষা করুন', marathi: 'आत्ताच पात्रता तपासा', gujarati: 'હવે પાત્રતા તપાસો', kannada: 'ಈಗಲೇ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ' }, lang),
  exploreTitle: p({ english: 'Explore Schemes by State', hindi: 'राज्य के अनुसार योजनाएं खोजें', tamil: 'மாநிலம் வாரியாக திட்டங்களை ஆராயுங்கள்', telugu: 'రాష్ట్రం వారీగా పథకాలు అన్వేషించండి', bengali: 'রাজ্য অনুযায়ী প্রকল্প অন্বেষণ করুন', marathi: 'राज्यानुसार योजना शोधा', gujarati: 'રાજ્ય પ્રમાણે યોજનાઓ શોધો', kannada: 'ರಾಜ್ಯದ ಪ್ರಕಾರ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ' }, lang),
  exploreSubtitle: p({ english: 'Click on any state to discover available schemes', hindi: 'उपलब्ध योजनाओं को जानने के लिए किसी भी राज्य पर क्लिक करें', tamil: 'கிடைக்கக்கூடிய திட்டங்களை கண்டறிய எந்த மாநிலத்திலும் கிளிக் செய்யுங்கள்', telugu: 'అందుబాటులో ఉన్న పథకాలు కనుగొనడానికి ఏదైనా రాష్ట్రంపై క్లిక్ చేయండి', bengali: 'উপলব্ধ প্রকল্পগুলি আবিষ্কার করতে যেকোনো রাজ্যে ক্লিক করুন', marathi: 'उपलब्ध योजना शोधण्यासाठी कोणत्याही राज्यावर क्लिक करा', gujarati: 'ઉપલબ્ધ યોજનાઓ શોધવા કોઈ પણ રાજ્ય પર ક્લિક કરો', kannada: 'ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ಯಾವುದೇ ರಾಜ್ಯದ ಮೇಲೆ ಕ್ಲಿಕ್ ಮಾಡಿ' }, lang),
  footerText: p({ english: 'JanVani Bharat — Built for people', hindi: 'जनवाणी भारत — लोगों के लिए', tamil: 'ஜன்வாணி பாரத் — மக்களுக்காக', telugu: 'జన్వాణి భారత్ — ప్రజల కోసం', bengali: 'জনবাণী ভারত — মানুষের জন্য', marathi: 'जनवाणी भारत — लोकांसाठी', gujarati: 'જનવાણી ભારત — લોકો માટે', kannada: 'ಜನವಾಣಿ ಭಾರತ — ಜನರಿಗಾಗಿ' }, lang),
  footerSub: p({ english: 'Empowering every citizen with AI-driven access to government welfare schemes.', hindi: 'AI-संचालित पहुंच के साथ हर नागरिक को सरकारी कल्याण योजनाओं तक सशक्त बनाना।', tamil: 'AI-இயக்கப்பட்ட அணுகலுடன் ஒவ்வொரு குடிமகனையும் அரசு நலத் திட்டங்களுக்கு வலுப்படுத்துகிறோம்.', telugu: 'AI-ఆధారిత యాక్సెస్‌తో ప్రతి పౌరుడిని ప్రభుత్వ సంక్షేమ పథకాలకు సాధికారత కల్పించడం.', bengali: 'AI-চালিত অ্যাক্সেসের মাধ্যমে প্রতিটি নাগরিককে সরকারি কল্যাণ প্রকল্পে ক্ষমতায়িত করা।', marathi: 'AI-चालित प्रवेशासह प्रत्येक नागरिकाला सरकारी कल्याण योजनांसाठी सक्षम करणे.', gujarati: 'AI-સંચાલિત ઍક્સેસ સાથે દરેક નાગરિકને સરકારી કલ્યાણ યોજનાઓ માટે સક્ષમ બનાવવા.', kannada: 'AI-ಚಾಲಿತ ಪ್ರವೇಶದೊಂದಿಗೆ ಪ್ರತಿ ನಾಗರಿಕರನ್ನು ಸರ್ಕಾರಿ ಕಲ್ಯಾಣ ಯೋಜನೆಗಳಿಗೆ ಸಶಕ್ತಗೊಳಿಸುವುದು.' }, lang),
  // Form
  formTitle: p({ english: 'Check Your Eligibility', hindi: 'अपनी पात्रता जांचें', tamil: 'உங்கள் தகுதியை சரிபார்க்கவும்', telugu: 'మీ అర్హత తనిఖీ చేయండి', bengali: 'আপনার যোগ্যতা পরীক্ষা করুন', marathi: 'तुमची पात्रता तपासा', gujarati: 'તમારી પાત્રતા તપાસો', kannada: 'ನಿಮ್ಮ ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ' }, lang),
  formSubtitle: p({ english: 'Fill in your details to discover government schemes you qualify for.', hindi: 'सरकारी योजनाओं के लिए अपना विवरण भरें।', tamil: 'நீங்கள் தகுதியான அரசு திட்டங்களை கண்டறிய உங்கள் விவரங்களை நிரப்புங்கள்.', telugu: 'మీరు అర్హత పొందిన ప్రభుత్వ పథకాలు కనుగొనడానికి వివరాలు నింపండి.', bengali: 'আপনি যোগ্য সরকারি প্রকল্পগুলি আবিষ্কার করতে আপনার তথ্য পূরণ করুন।', marathi: 'तुम्ही पात्र असलेल्या सरकारी योजना शोधण्यासाठी तपशील भरा.', gujarati: 'તમે પાત્ર સરકારી યોજનાઓ શોધવા તમારી વિગતો ભરો.', kannada: 'ನೀವು ಅರ್ಹರಾಗಿರುವ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ತುಂಬಿರಿ.' }, lang),
  analyzing: p({ english: 'Analyzing your eligibility...', hindi: 'आपकी पात्रता का विश्लेषण हो रहा है...', tamil: 'உங்கள் தகுதியை பகுப்பாய்வு செய்கிறோம்...', telugu: 'మీ అర్హతను విశ్లేషిస్తున్నాము...', bengali: 'আপনার যোগ্যতা বিশ্লেষণ করা হচ্ছে...', marathi: 'तुमची पात्रता विश्लेषण केली जात आहे...', gujarati: 'તમારી પાત્રતા વિશ્લેષણ કરવામાં આવી રહ્યું છે...', kannada: 'ನಿಮ್ಮ ಅರ್ಹತೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...' }, lang),
  analyzingSubtitle: p({ english: 'Our AI is matching your profile with government schemes', hindi: 'हमारा AI आपकी प्रोफ़ाइल को सरकारी योजनाओं से मिला रहा है', tamil: 'எங்கள் AI உங்கள் சுயவிவரத்தை அரசு திட்டங்களுடன் பொருத்துகிறது', telugu: 'మా AI మీ ప్రొఫైల్‌ను ప్రభుత్వ పథకాలతో సరిపోల్చుతోంది', bengali: 'আমাদের AI আপনার প্রোফাইল সরকারি প্রকল্পের সাথে মেলাচ্ছে', marathi: 'आमचे AI तुमची प्रोफाइल सरकारी योजनांशी जुळवत आहे', gujarati: 'અમારું AI તમારી પ્રોફાઇલ સરકારી યોજનાઓ સાથે મેળ ખાય છે', kannada: 'ನಮ್ಮ AI ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳೊಂದಿಗೆ ಹೊಂದಿಸುತ್ತಿದೆ' }, lang),
  checkBtn: p({ english: 'Check Eligibility', hindi: 'पात्रता जांचें', tamil: 'தகுதி சரிபார்க்கவும்', telugu: 'అర్హత తనిఖీ', bengali: 'যোগ্যতা পরীক্ষা', marathi: 'पात्रता तपासा', gujarati: 'પાત્રતા તપાસો', kannada: 'ಅರ್ಹತೆ ಪರಿಶೀಲಿಸಿ' }, lang),
  fullName: p({ english: 'Full Name', hindi: 'पूरा नाम', tamil: 'முழு பெயர்', telugu: 'పూర్తి పేరు', bengali: 'পুরো নাম', marathi: 'पूर्ण नाव', gujarati: 'પૂરું નામ', kannada: 'ಪೂರ್ಣ ಹೆಸರು' }, lang),
  namePlaceholder: p({ english: 'Enter your full name', hindi: 'अपना पूरा नाम दर्ज करें', tamil: 'உங்கள் முழு பெயரை உள்ளிடுங்கள்', telugu: 'మీ పూర్తి పేరు నమోదు చేయండి', bengali: 'আপনার পুরো নাম লিখুন', marathi: 'तुमचे पूर्ण नाव टाका', gujarati: 'તમારું પૂરું નામ દાખલ કરો', kannada: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ' }, lang),
  age: p({ english: 'Age', hindi: 'आयु', tamil: 'வயது', telugu: 'వయసు', bengali: 'বয়স', marathi: 'वय', gujarati: 'ઉંમર', kannada: 'ವಯಸ್ಸು' }, lang),
  gender: p({ english: 'Gender', hindi: 'लिंग', tamil: 'பாலினம்', telugu: 'లింగం', bengali: 'লিঙ্গ', marathi: 'लिंग', gujarati: 'લિંગ', kannada: 'ಲಿಂಗ' }, lang),
  male: p({ english: 'Male', hindi: 'पुरुष', tamil: 'ஆண்', telugu: 'పురుషుడు', bengali: 'পুরুষ', marathi: 'पुरुष', gujarati: 'પુરુષ', kannada: 'ಪುರುಷ' }, lang),
  female: p({ english: 'Female', hindi: 'महिला', tamil: 'பெண்', telugu: 'మహిళ', bengali: 'মহিলা', marathi: 'महिला', gujarati: 'સ્ત્રી', kannada: 'ಮಹಿಳೆ' }, lang),
  other: p({ english: 'Other', hindi: 'अन्य', tamil: 'மற்றவை', telugu: 'ఇతర', bengali: 'অন্যান্য', marathi: 'इतर', gujarati: 'અન્ય', kannada: 'ಇತರ' }, lang),
  income: p({ english: 'Annual Income (₹)', hindi: 'वार्षिक आय (₹)', tamil: 'வருடாந்திர வருமானம் (₹)', telugu: 'వార్షిక ఆదాయం (₹)', bengali: 'বার্ষিক আয় (₹)', marathi: 'वार्षिक उत्पन्न (₹)', gujarati: 'વાર્ષિક આવક (₹)', kannada: 'ವಾರ್ಷಿಕ ಆದಾಯ (₹)' }, lang),
  state: p({ english: 'State / Union Territory', hindi: 'राज्य / केंद्र शासित प्रदेश', tamil: 'மாநிலம் / யூனியன் பிரதேசம்', telugu: 'రాష్ట్రం / కేంద్రపాలిత ప్రాంతం', bengali: 'রাজ্য / কেন্দ্রশাসিত অঞ্চল', marathi: 'राज्य / केंद्रशासित प्रदेश', gujarati: 'રાજ્ય / કેન્દ્રશાસિત પ્રદેશ', kannada: 'ರಾಜ್ಯ / ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶ' }, lang),
  selectState: p({ english: 'Select your state', hindi: 'अपना राज्य चुनें', tamil: 'உங்கள் மாநிலத்தை தேர்ந்தெடுங்கள்', telugu: 'మీ రాష్ట్రం ఎంచుకోండి', bengali: 'আপনার রাজ্য নির্বাচন করুন', marathi: 'तुमचे राज्य निवडा', gujarati: 'તમારું રાજ્ય પસંદ કરો', kannada: 'ನಿಮ್ಮ ರಾಜ್ಯ ಆಯ್ಕೆ ಮಾಡಿ' }, lang),
  area: p({ english: 'Area', hindi: 'क्षेत्र', tamil: 'பகுதி', telugu: 'ప్రాంతం', bengali: 'এলাকা', marathi: 'क्षेत्र', gujarati: 'વિસ્તાર', kannada: 'ಪ್ರದೇಶ' }, lang),
  rural: p({ english: 'Rural', hindi: 'ग्रामीण', tamil: 'கிராமப்புறம்', telugu: 'గ్రామీణ', bengali: 'গ্রামীণ', marathi: 'ग्रामीण', gujarati: 'ગ્રામીણ', kannada: 'ಗ್ರಾಮೀಣ' }, lang),
  urban: p({ english: 'Urban', hindi: 'शहरी', tamil: 'நகர்ப்புறம்', telugu: 'పట్టణ', bengali: 'শহুরে', marathi: 'शहरी', gujarati: 'શહેરી', kannada: 'ನಗರ' }, lang),
  category: p({ english: 'Category', hindi: 'श्रेणी', tamil: 'வகை', telugu: 'వర్గం', bengali: 'বিভাগ', marathi: 'श्रेणी', gujarati: 'શ્રેણી', kannada: 'ವರ್ಗ' }, lang),
  occupation: p({ english: 'Occupation', hindi: 'व्यवसाय', tamil: 'தொழில்', telugu: 'వృత్తి', bengali: 'পেশা', marathi: 'व्यवसाय', gujarati: 'વ્યવસાય', kannada: 'ಉದ್ಯೋಗ' }, lang),
  selectOccupation: p({ english: 'Select your occupation', hindi: 'अपना व्यवसाय चुनें', tamil: 'உங்கள் தொழிலை தேர்ந்தெடுங்கள்', telugu: 'మీ వృత్తి ఎంచుకోండి', bengali: 'আপনার পেশা নির্বাচন করুন', marathi: 'तुमचा व्यवसाय निवडा', gujarati: 'તમારો વ્યવસાય પસંદ કરો', kannada: 'ನಿಮ್ಮ ಉದ್ಯೋಗ ಆಯ್ಕೆ ಮಾಡಿ' }, lang),
  occupations: {
    farmer: p({ english: 'Farmer', hindi: 'किसान', tamil: 'விவசாயி', telugu: 'రైతు', bengali: 'কৃষক', marathi: 'शेतकरी', gujarati: 'ખેડૂત', kannada: 'ರೈತ' }, lang),
    student: p({ english: 'Student', hindi: 'छात्र', tamil: 'மாணவர்', telugu: 'విద్యార్థి', bengali: 'ছাত্র', marathi: 'विद्यार्थी', gujarati: 'વિદ્યાર્થી', kannada: 'ವಿದ್ಯಾರ್ಥಿ' }, lang),
    business: p({ english: 'Business Owner', hindi: 'व्यापारी', tamil: 'வணிகர்', telugu: 'వ్యాపారి', bengali: 'ব্যবসায়ী', marathi: 'व्यापारी', gujarati: 'વ્યાપારી', kannada: 'ವ್ಯಾಪಾರಿ' }, lang),
    'self-employed': p({ english: 'Self-Employed', hindi: 'स्वरोजगार', tamil: 'சுயதொழில்', telugu: 'స్వయం ఉపాధి', bengali: 'স্ব-নিযুক্ত', marathi: 'स्वयंरोजगार', gujarati: 'સ્વ-રોજગાર', kannada: 'ಸ್ವ-ಉದ್ಯೋಗ' }, lang),
    employed: p({ english: 'Salaried Employee', hindi: 'वेतनभोगी कर्मचारी', tamil: 'சம்பளதாரர்', telugu: 'జీతగాడు', bengali: 'বেতনভোগী কর্মচারী', marathi: 'पगारदार कर्मचारी', gujarati: 'પગારદાર કર્મચારી', kannada: 'ವೇತನ ನೌಕರ' }, lang),
    labourer: p({ english: 'Daily Wage Labourer', hindi: 'दैनिक मजदूर', tamil: 'தினக்கூலி தொழிலாளி', telugu: 'రోజువారీ కూలీ', bengali: 'দৈনিক মজুর', marathi: 'दैनिक मजूर', gujarati: 'દૈનિક મજૂર', kannada: 'ದಿನಗೂಲಿ ಕಾರ್ಮಿಕ' }, lang),
    unemployed: p({ english: 'Unemployed', hindi: 'बेरोजगार', tamil: 'வேலையற்றவர்', telugu: 'నిరుద్యోగి', bengali: 'বেকার', marathi: 'बेरोजगार', gujarati: 'બેરોજગાર', kannada: 'ನಿರುದ್ಯೋಗಿ' }, lang),
    retired: p({ english: 'Retired', hindi: 'सेवानिवृत्त', tamil: 'ஓய்வுபெற்றவர்', telugu: 'పదవీ విరమణ', bengali: 'অবসরপ্রাপ্ত', marathi: 'निवृत्त', gujarati: 'નિવૃત્ત', kannada: 'ನಿವೃತ್ತ' }, lang),
  },
  // Results page
  eligibleSchemes: p({ english: 'Eligible Schemes', hindi: 'पात्र योजनाएं', tamil: 'தகுதியான திட்டங்கள்', telugu: 'అర్హత పొందిన పథకాలు', bengali: 'যোগ্য প্রকল্পসমূহ', marathi: 'पात्र योजना', gujarati: 'પાત્ર યોજનાઓ', kannada: 'ಅರ್ಹ ಯೋಜನೆಗಳು' }, lang),
  benefits: p({ english: 'Benefits', hindi: 'लाभ', tamil: 'நன்மைகள்', telugu: 'ప్రయోజనాలు', bengali: 'সুবিধা', marathi: 'फायदे', gujarati: 'ફાયદા', kannada: 'ಪ್ರಯೋಜನಗಳು' }, lang),
  applyNow: p({ english: 'Apply Now', hindi: 'अभी आवेदन करें', tamil: 'இப்போது விண்ணப்பிக்கவும்', telugu: 'ఇప్పుడు దరఖాస్తు చేయండి', bengali: 'এখনই আবেদন করুন', marathi: 'आत्ताच अर्ज करा', gujarati: 'હવે અરજી કરો', kannada: 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ' }, lang),
  noSchemes: p({ english: 'No matching schemes found at this time.', hindi: 'इस समय कोई उपयुक्त योजना नहीं मिली।', tamil: 'தற்போது பொருத்தமான திட்டங்கள் எதுவும் கிடைக்கவில்லை.', telugu: 'ప్రస్తుతం సరిపోలే పథకాలు ఏవీ కనుగొనబడలేదు.', bengali: 'এই মুহূর্তে কোনো মিলে যাওয়া প্রকল্প পাওয়া যায়নি।', marathi: 'सध्या कोणत्याही जुळणाऱ्या योजना आढळल्या नाहीत.', gujarati: 'આ સમયે કોઈ મેળ ખાતી યોજનાઓ મળી નથી.', kannada: 'ಈ ಸಮಯದಲ್ಲಿ ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಯ ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.' }, lang),
  noSchemesHint: p({ english: 'Try visiting your nearest Common Service Centre (CSC) for personalized assistance.', hindi: 'व्यक्तिगत सहायता के लिए अपने निकटतम CSC पर जाएं।', tamil: 'தனிப்பட்ட உதவிக்கு உங்கள் அருகிலுள்ள CSC-ஐ அணுகவும்.', telugu: 'వ్యక్తిగత సహాయం కోసం సమీప CSC సందర్శించండి.', bengali: 'ব্যক্তিগত সহায়তার জন্য নিকটতম CSC পরিদর্শন করুন।', marathi: 'वैयक्तिक मदतीसाठी जवळच्या CSC ला भेट द्या.', gujarati: 'વ્યક્તિગત સહાય માટે નજીકના CSC ની મુલાકાત લો.', kannada: 'ವ್ಯಕ್ತಿಗತ ಸಹಾಯಕ್ಕಾಗಿ ಹತ್ತಿರದ CSC ಗೆ ಭೇಟಿ ನೀಡಿ.' }, lang),
  aiExplanation: p({ english: 'AI Explanation', hindi: 'AI स्पष्टीकरण', tamil: 'AI விளக்கம்', telugu: 'AI వివరణ', bengali: 'AI ব্যাখ্যা', marathi: 'AI स्पष्टीकरण', gujarati: 'AI સ્પષ્ટીકરણ', kannada: 'AI ವಿವರಣೆ' }, lang),
  checkAgain: p({ english: 'Check Again', hindi: 'फिर से जांचें', tamil: 'மீண்டும் சரிபார்க்கவும்', telugu: 'మళ్ళీ తనిఖీ చేయండి', bengali: 'আবার পরীক্ষা করুন', marathi: 'पुन्हा तपासा', gujarati: 'ફરી તપાસો', kannada: 'ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ' }, lang),
  checkAnother: p({ english: 'Check Another Profile', hindi: 'दूसरी प्रोफ़ाइल जांचें', tamil: 'மற்றொரு சுயவிவரம் சரிபார்க்கவும்', telugu: 'మరొక ప్రొఫైల్ తనిఖీ చేయండి', bengali: 'আরেকটি প্রোফাইল পরীক্ষা করুন', marathi: 'दुसरी प्रोफाइल तपासा', gujarati: 'બીજી પ્રોફાઇલ તપાસો', kannada: 'ಮತ್ತೊಂದು ಪ್ರೊಫೈಲ್ ಪರಿಶೀಲಿಸಿ' }, lang),
  schemesFound: (count: number, name: string) => {
    const templates: Record<Language, string> = {
      english: `${count} scheme${count !== 1 ? 's' : ''} found for ${name}`,
      hindi: `${name} के लिए ${count} योजनाएं मिलीं`,
      tamil: `${name} க்கு ${count} திட்டங்கள் கிடைத்தன`,
      telugu: `${name} కోసం ${count} పథకాలు కనుగొనబడ్డాయి`,
      bengali: `${name} এর জন্য ${count}টি প্রকল্প পাওয়া গেছে`,
      marathi: `${name} साठी ${count} योजना सापडल्या`,
      gujarati: `${name} માટે ${count} યોજનાઓ મળી`,
      kannada: `${name} ಗಾಗಿ ${count} ಯೋಜನೆಗಳು ಕಂಡುಬಂದಿವೆ`,
    };
    return templates[lang] ?? templates.english;
  },
  // Chatbot
  chatGreeting: p({ english: 'Hello! I\'m JanVani AI. Ask me about any government scheme.', hindi: 'नमस्ते! मैं जनवाणी AI हूं। किसी भी सरकारी योजना के बारे में पूछें।', tamil: 'வணக்கம்! நான் ஜன்வாணி AI. எந்த அரசு திட்டத்தைப் பற்றியும் கேளுங்கள்.', telugu: 'నమస్కారం! నేను జన్వాణి AI. ఏదైనా ప్రభుత్వ పథకం గురించి అడగండి.', bengali: 'নমস্কার! আমি জনবাণী AI। যেকোনো সরকারি প্রকল্প সম্পর্কে জিজ্ঞেস করুন।', marathi: 'नमस्कार! मी जनवाणी AI आहे. कोणत्याही सरकारी योजनेबद्दल विचारा.', gujarati: 'નમસ્તે! હું જનવાણી AI છું. કોઈ પણ સરકારી યોજના વિશે પૂછો.', kannada: 'ನಮಸ್ಕಾರ! ನಾನು ಜನವಾಣಿ AI. ಯಾವುದೇ ಸರ್ಕಾರಿ ಯೋಜನೆ ಬಗ್ಗೆ ಕೇಳಿ.' }, lang),
  chatPlaceholder: p({ english: 'Ask about any government scheme...', hindi: 'किसी भी सरकारी योजना के बारे में पूछें...', tamil: 'எந்த அரசு திட்டத்தைப் பற்றியும் கேளுங்கள்...', telugu: 'ఏదైనా ప్రభుత్వ పథకం గురించి అడగండి...', bengali: 'যেকোনো সরকারি প্রকল্প সম্পর্কে জিজ্ঞেস করুন...', marathi: 'कोणत्याही सरकारी योजनेबद्दल विचारा...', gujarati: 'કોઈ પણ સરકારી યોજના વિશે પૂછો...', kannada: 'ಯಾವುದೇ ಸರ್ಕಾರಿ ಯೋಜನೆ ಬಗ್ಗೆ ಕೇಳಿ...' }, lang),
});
